### ISSUE TITLE
What does RuntimeCryptographyProvider do?

### ISSUE THREAD

**Issue by libdev-hacker** [arleypadua/PKHeX.Everywhere#101]
I was reading through the code & found your workaround for .NET not supporting certain crypto algorithms. I tried looking for a definition for this but I can't find anything online about, could you explain what it does & potentially where I could find out more about it?

https://github.com/arleypadua/PKHeX.Everywhere/blob/c9c30deff2c4285ef549cfbe4c3400443290c1cc/src/PKHeX.Web/Program.cs#L110

**Comment by arleypadua** [comment]
The whole issue starts with the fact that the build target of PKHeX.Web is Blazor WASM, and although the .Net Framework has a standard lib to deal with these sort of issues, the namespace `System.Security.Cryptography` [is not really supported on Blazor WASM](https://learn.microsoft.com/en-us/dotnet/core/compatibility/cryptography/5.0/cryptography-apis-not-supported-on-blazor-webassembly)

This, in conjunction with the fact that [PKHeX.Core](https://github.com/kwsch/PKHeX) relies on this namespace to execute some operations when encrypting/decrypting save files

So, the idea was to [write an extension within PKHex.Core](https://github.com/kwsch/PKHeX/pull/4311) (aka `RuntimeCryptographyProvider`, that allows external consumers of the library to override the cryptography provider at runtime

By default it supports the .NET Framework standard crypto library, but when used like the way you referred:

```csharp
RuntimeCryptographyProvider.Aes = app.Services.GetRequiredService<BlazorAesProvider>(); 
```

It will use the class `BlazorAesProvider` as the provider, which is backed by `crypto-js`

https://github.com/arleypadua/PKHeX.Everywhere/blob/c9c30deff2c4285ef549cfbe4c3400443290c1cc/src/PKHeX.Web/_js/lib/crypto/aes.ts#L3-L10

https://github.com/arleypadua/PKHeX.Everywhere/blob/c9c30deff2c4285ef549cfbe4c3400443290c1cc/src/PKHeX.Web/_js/lib/crypto/aes.ts#L12-L21
