### ISSUE TITLE
Fail to export Switch save file

### ISSUE THREAD

**Issue by UsRnM44** [arleypadua/PKHeX.Everywhere#107]
It's either because I do not have experience with PKHeX so much, but when using the PKHeX web editing switch "main" file, upon saving the browser makes it .txt file, showing it's "text file" on mac rather than "document".

**Comment by arleypadua** [comment]
Thanks for sharing

This is a known bug, to workaround it, just remove the .txt extension and it should be good

I will try to find some time and see if there's a fix for it

**Comment by UsRnM44** [comment]
> Thanks for sharing
> 
> This is a known bug, to workaround it, just remove the .txt extension and it should be good
> 
> I will try to find some time and see if there's a fix for it

In Mac just removing it doesn't work, the system still defines it as text document.
I actually managed to workaround this using the Safari browser and not Chrome.

**Comment by arleypadua** [comment]
From what I've been searching, it seems a default behavior of Chromium-based browsers (Edge/Chrome) to put txt on files that don't have extension.

Will push a workaround in a bit, hopefully it works 🤞🏽

**Comment by arleypadua** [comment]
From what I've been testing, this issue seems to be fixed. 

I will close this issue, but If you still have issues let me know
