### ISSUE TITLE
Install script can't fetch the latest release 

### ISSUE THREAD

**Issue by dallenbaldwin** [arleypadua/PKHeX.Everywhere#48]
When following the shell installation steps from the README, I get the following error (there was no root prompt because I was already authed as root)

```bash
curl -sL https://raw.githubusercontent.com/arleypadua/PKHeX.CLI/main/install.sh | sudo bash

Error: Could not fetch the latest release URL. Please check your GitHub repository and artifact name.
```

**Comment by arleypadua** [comment]
Thanks for the feedback.

Recently I renamed the repository and left some places with the old reference, which was causing the issue. It has been fixed now.
