### ISSUE TITLE
Install script will fail for Steam Deck Users

### ISSUE THREAD

**Issue by dallenbaldwin** [arleypadua/PKHeX.Everywhere#49]
I couldn't get the install script to find the latest binary so I went to follow the manually install it by looking over the install script to replicate what I could with the manually downloaded binary.

I'm using a Steam Deck and  SteamOS uses a read only file system, making it impossible to move the binary to `/usr/local/bin`

As far as I know, even when you enable developer mode, the root file system will be reset with every major update to SteamOS. Only files in the user space, and probably a couple others I'm not aware of, are preserved.

To get around all this and get it working

1. Manually download the latest release and extract the bin
2. Move the bin to `~/.local/bin`
3. Updated the PATH variable in `~/.bashrc`

```sh
PATH="$PATH:$HOME/.local/bin"
```

I don't want to assert my workaround is the best way to deal with a read only file system.

For future users, possibly a "best practice manual installation" for read only file systems would be nice to have more readily available

**Comment by arleypadua** [comment]
That's a good tip, I'm not an expert with linux and it's file system, but seems better to store on the user path rather than on the system path

Updated the script to use ~/.local/bin folder
