### ISSUE TITLE
[Feature] Ability to modify .pk files

### ISSUE THREAD

**Issue by KintsugiUwU** [arleypadua/PKHeX.Everywhere#51]
Would be nice to have the ability to modify single pokemons instead of whole save files. Not having a modded switch I can't extract my save file, but I can trade pokemon to bots which gave me .pk files

**Comment by arleypadua** [comment]
Yup, thanks for the feedback.

Interesting use case. 

Will keep this issue opened and when I find some time, will try to pull something out.

**Comment by KintsugiUwU** [comment]
Thanks, as a quick way to edit some pokemon, your tool works perfectly. May I ask how can I change the TID/SID and OT Name of a pokemon imported? Can't seem to find the option?

**Comment by arleypadua** [comment]
> Thanks, as a quick way to edit some pokemon, your tool works perfectly. May I ask how can I change the TID/SID and OT Name of a pokemon imported? Can't seem to find the option?

That's indeed missing, as it wasn't necessary before the importing of Pokemon files. Will look into adding it, should be simple.
