### ISSUE TITLE
Any chance of a 32bit linux version?

### ISSUE THREAD

**Issue by rkr87** [arleypadua/PKHeX.Everywhere#61]
I'm trying to get this working on a TrimUI Smart Pro - would be great if there was a 32 bit version.

**Comment by arleypadua** [comment]
Last time I checked, Microsoft does not support Linux x86 as a target 😞 

I guess it supports linux-arm32, maybe worth trying out... will change the pipeline also to output a arm32 and hopefully it works

**Comment by arleypadua** [comment]
unfortunately not supported as of now

> Ahead-of-time compilation is not supported for the target runtime identifier 'linux-arm32'
