### ISSUE TITLE
An unhandled error has occurred.

### ISSUE THREAD

**Issue by Panky55** [arleypadua/PKHeX.Everywhere#63]
I get the error An unhandled error has occurred. when trying to load the web page and it just stays at loading 100%

**Comment by arleypadua** [comment]
I've seen this happening before on some versions of iPad and iOS.

Can you confirm what device/os version you are using?

**Comment by Panky55** [comment]
I’m using an iPhone

**Comment by Panky55** [comment]
> I've seen this happening before on some versions of iPad and iOS.
> 
> Can you confirm what device/os version you are using?

And I’m on iOS 15.8.2

**Comment by arleypadua** [comment]
can't reproduce the issue
