### ISSUE TITLE
Editing the save file directly

### ISSUE THREAD

**Issue by GorgleLot** [arleypadua/PKHeX.Everywhere#80]
Hello, to whoever is reading this.
Now I like the Pkhex program, I like it very much, but I thought, if possible, a feature where you can edit your save files directly instead of making a copy would be very convenient and effective. 
That's all I had to say, nothing more.
Good day

**Comment by arleypadua** [comment]
The nature of a web based version won't allow to edit files directly.

That will be possible with the [CLI version](https://github.com/arleypadua/PKHeX.Everywhere/tree/main/src/PKHeX.CLI) or the original [PKHeX for Windows](https://projectpokemon.org/home/files/file/1-pkhex/)
