### ISSUE TITLE
Base stats are all 0

### ISSUE THREAD

**Issue by john-champagne** [arleypadua/PKHeX.Everywhere#88]
Testing out the web version, I opened my Pokemon Platinum save file. When I hit `Pokemon Box > Action > View > Stats`, the 'Base' column is all zero.

![image](https://github.com/user-attachments/assets/85c29945-f8c6-4ebc-84c8-a3e4324f303a)

This appears to be the case for all my Pokemon in the `Pokemon Box`. Weirdly, Pokemon in my party do not have the same issue.

**Comment by arleypadua** [comment]
This is not a bug, it is the nature some of the games store the data in the save files.

For most games, the base stats of Pokemon in your box are not stored, only the ones in your party.

One game I could see is an exception to this rule is for instance Let's Go Pikachu, where I could see those values in the box as well

**Comment by john-champagne** [comment]
Interesting; thanks for the quick response. I believe the PKHeX windows build shows base stats for Pokemon in the box. I presume it's just reading from a large table of base stats?

**Comment by arleypadua** [comment]
Thanks for the input on this @john-champagne 

Just pushed [c9c30de](https://github.com/arleypadua/PKHeX.Everywhere/commit/c9c30deff2c4285ef549cfbe4c3400443290c1cc), which should always calculate a base stats when one is not available

**Comment by john-champagne** [comment]
💯 thanks Arley!
