### ISSUE TITLE
PKHeX web

### ISSUE THREAD

**Issue by Guttilex** [arleypadua/PKHeX.Everywhere#92]
Hi there, I have been having some issues on PKHeX web, because I have a MacBook and it's very complicated to download PKHeX I tried the web version, but every time I try to insert my save file or the Pokemon game I play on city, it says that the file is too large, and I don't know what to do anymore. 
I hope to hear back from you soon.

Thank you
Best wishes 
<img width="1470" alt="Captura de Tela 2024-11-10 às 00 08 36" src="https://github.com/user-attachments/assets/5c1c5681-d0c4-4723-b761-3d7db2df5baa">
Oliver

**Comment by Awetspoon** [comment]
hello is your nature changing working as mine isnt ?

**Comment by arleypadua** [comment]
> Hi there, I have been having some issues on PKHeX web, because I have a MacBook and it's very complicated to download PKHeX I tried the web version, but every time I try to insert my save file or the Pokemon game I play on city, it says that the file is too large, and I don't know what to do anymore. I hope to hear back from you soon.
> 
> Thank you Best wishes <img alt="Captura de Tela 2024-11-10 às 00 08 36" width="1470" src="https://private-user-images.githubusercontent.com/164553361/384649808-5c1c5681-d0c4-4723-b761-3d7db2df5baa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NTkwNjMsIm5iZiI6MTczMTY1ODc2MywicGF0aCI6Ii8xNjQ1NTMzNjEvMzg0NjQ5ODA4LTVjMWM1NjgxLWQwYzQtNDcyMy1iNzYxLTNkN2RiMmRmNWJhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNVQwODE5MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDk4N2E4Yzg3NTJiNzRlODEyN2IyY2Y3NzRmN2E0MjVhMTI3MThmNzhiZGE2NjkyMWVmZmFiNDQ5M2FhMTlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.NX7IaQiXyym-1a2aOn9MmnYLVxtL0qLpnSmIDPrWRRU"> Oliver

What's the name of the file you're loading into the app? It only supports save files. 

Save states are not supported

**Comment by arleypadua** [comment]
> hello is your nature changing working as mine isnt ?

To avoid confusion we usually open a new issue if it is voor related to any other opened, but I see that editing nature is indeed not working... Will look into it

Issue tracker: https://github.com/arleypadua/PKHeX.Everywhere/issues/95

**Comment by Awetspoon** [comment]
Sorry about that I'll be sure top post in future sorry again

**Comment by arleypadua** [comment]
Closing this as it doesn't seem to be an issue related to pkhex web
